# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[lint]

# E - PEP 8 errors (e.g., indentation issues, syntax errors)
# W - PEP 8 warnings (e.g., line length, whitespace usage)
# F - Pyflakes: checks for logical errors (e.g., undefined variables, unused imports)
# B - Flake8-Bugbear: finds common bugs and design problems (e.g., mutable default arguments)
# C - McCabe Complexity: checks for overly complex code (high cyclomatic complexity)
# N - PEP 8 Naming Conventions: enforces naming conventions for variables, functions, and classes
# S - Bandit Security Linter: checks for common security issues (e.g., insecure functions, hardcoded passwords)
# ANN - Flake8-Annotated: checks for missing type annotations
# D - Pydocstyle: enforces the presence of docstrings in modules, classes, and functions

select = ["E", "W", "F", "B", "C", "N", "S", "ANN", "D"]

ignore = [
    # E501 - "line too long", its function is replaced by `flake8-length`
    "E501",

    # W505 - "doc line too long", its function is replaced by `flake8-length`
    "W505",

    # I - flake8-isort is drunk + we have isort integrated into pre-commit
    "I",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
